import React, { useState, useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { 
  getHistoryItem, 
  updateSkillConfidence, 
  calculateLiveScore, 
  getWeakSkills 
} from '../utils/skillAnalyzer';
import CompanyIntel from './CompanyIntel';

const ResultsPage = () => {
  const { id } = useParams();
  const navigate = useNavigate();
  const [analysisData, setAnalysisData] = useState(null);
  const [activeTab, setActiveTab] = useState('skills');
  const [liveScore, setLiveScore] = useState(0);
  const [skillConfidenceMap, setSkillConfidenceMap] = useState({});

  useEffect(() => {
    if (id) {
      const historyItem = getHistoryItem(id);
      if (historyItem) {
        setAnalysisData(historyItem);
        setLiveScore(historyItem.readinessScore);
        setSkillConfidenceMap(historyItem.skillConfidenceMap || {});
      } else {
        navigate('/analysis');
      }
    }
  }, [id, navigate]);

  const handleSkillToggle = (skill, currentConfidence) => {
    const newConfidence = currentConfidence === 'know' ? 'practice' : 'know';
    const updatedMap = { ...skillConfidenceMap, [skill]: newConfidence };
    setSkillConfidenceMap(updatedMap);
    
    // Update in localStorage
    const updatedItem = updateSkillConfidence(id, skill, newConfidence);
    if (updatedItem) {
      // Calculate new live score
      const newScore = calculateLiveScore(
        updatedItem.readinessScore, 
        updatedMap, 
        updatedItem.extractedSkills
      );
      setLiveScore(newScore);
    }
  };

  const copyToClipboard = (text) => {
    navigator.clipboard.writeText(text);
  };

  const exportAllAsText = () => {
    if (!analysisData) return;
    
    const content = `
PLACEMENT READINESS ANALYSIS
============================
Company: ${analysisData.company}
Role: ${analysisData.role}
Date: ${new Date(analysisData.createdAt).toLocaleDateString()}

READINESS SCORE: ${liveScore}/100

KEY SKILLS EXTRACTED:
${Object.entries(analysisData.extractedSkills)
  .map(([category, skills]) => `${category}:\n${skills.map(skill => `  • ${skill} [${skillConfidenceMap[skill] || 'practice'}]`).join('\n')}`)
  .join('\n\n')}

7-DAY PREPARATION PLAN:
${Object.entries(analysisData.plan)
  .map(([day, items]) => `${day}:\n${items.map(item => `  • ${item}`).join('\n')}`)
  .join('\n\n')}

ROUND-WISE CHECKLIST:
${Object.entries(analysisData.checklist)
  .map(([round, items]) => `${round}:\n${items.map(item => `  • ${item}`).join('\n')}`)
  .join('\n\n')}

INTERVIEW QUESTIONS:
${analysisData.questions.map((q, i) => `${i + 1}. ${q}`).join('\n')}

Generated by Placement Readiness Platform
    `.trim();
    
    copyToClipboard(content);
    alert('Full analysis copied to clipboard!');
  };

  const copySection = (section) => {
    if (!analysisData) return;
    
    let content = '';
    switch (section) {
      case 'plan':
        content = Object.entries(analysisData.plan)
          .map(([day, items]) => `${day}:\n${items.map(item => `  • ${item}`).join('\n')}`)
          .join('\n\n');
        break;
      case 'checklist':
        content = Object.entries(analysisData.checklist)
          .map(([round, items]) => `${round}:\n${items.map(item => `  • ${item}`).join('\n')}`)
          .join('\n\n');
        break;
      case 'questions':
        content = analysisData.questions.map((q, i) => `${i + 1}. ${q}`).join('\n');
        break;
      default:
        return;
    }
    
    copyToClipboard(content);
    alert(`${section.charAt(0).toUpperCase() + section.slice(1)} copied to clipboard!`);
  };

  const getWeakSkillsList = () => {
    if (!analysisData) return [];
    return getWeakSkills(skillConfidenceMap, analysisData.extractedSkills);
  };

  if (!analysisData) {
    return (
      <div className="flex justify-center items-center h-64">
        <div className="text-center">
          <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-primary-500 mx-auto"></div>
          <p className="mt-4 text-gray-600">Loading analysis...</p>
        </div>
      </div>
    );
  }

  const tabs = [
    { id: 'skills', label: 'Key Skills' },
    { id: 'checklist', label: 'Preparation Checklist' },
    { id: 'plan', label: '7-Day Plan' },
    { id: 'questions', label: 'Interview Questions' }
  ];

  const weakSkills = getWeakSkillsList();

  return (
    <div className="max-w-6xl mx-auto">
      {/* Header */}
      <div className="card mb-6">
        <div className="flex flex-col md:flex-row md:items-center md:justify-between">
          <div>
            <h1 className="text-3xl font-bold text-gray-900">Analysis Results</h1>
            <p className="text-gray-600 mt-2">
              {analysisData.company} • {analysisData.role} • {new Date(analysisData.createdAt).toLocaleDateString()}
            </p>
          </div>
          <div className="mt-4 md:mt-0">
            <div className="text-center">
              <div className="text-5xl font-bold text-primary-600">
                {liveScore}
              </div>
              <div className="text-gray-600">Readiness Score</div>
              <div className="text-sm text-gray-500 mt-1">
                (Live update based on self-assessment)
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Export Buttons */}
      <div className="card mb-6">
        <h3 className="text-lg font-semibold text-gray-900 mb-4">Export Options</h3>
        <div className="flex flex-wrap gap-3">
          <button 
            onClick={() => copySection('plan')}
            className="px-4 py-2 bg-blue-100 text-blue-800 rounded-lg hover:bg-blue-200 transition-colors"
          >
            Copy 7-day Plan
          </button>
          <button 
            onClick={() => copySection('checklist')}
            className="px-4 py-2 bg-green-100 text-green-800 rounded-lg hover:bg-green-200 transition-colors"
          >
            Copy Round Checklist
          </button>
          <button 
            onClick={() => copySection('questions')}
            className="px-4 py-2 bg-purple-100 text-purple-800 rounded-lg hover:bg-purple-200 transition-colors"
          >
            Copy 10 Questions
          </button>
          <button 
            onClick={exportAllAsText}
            className="px-4 py-2 bg-gray-100 text-gray-800 rounded-lg hover:bg-gray-200 transition-colors"
          >
            Download as TXT
          </button>
        </div>
      </div>

      {/* Tabs */}
      <div className="card mb-6">
        <div className="border-b border-gray-200">
          <nav className="-mb-px flex space-x-8">
            {tabs.map((tab) => (
              <button
                key={tab.id}
                onClick={() => setActiveTab(tab.id)}
                className={`py-4 px-1 border-b-2 font-medium text-sm ${
                  activeTab === tab.id
                    ? 'border-primary-500 text-primary-600'
                    : 'border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300'
                }`}
              >
                {tab.label}
              </button>
            ))}
          </nav>
        </div>
      </div>

      {/* Tab Content */}
      <div className="card mb-6">
        {activeTab === 'skills' && (
          <div>
            <h3 className="text-xl font-semibold text-gray-900 mb-6">Key Skills Assessment</h3>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              {Object.entries(analysisData.extractedSkills).map(([category, skills]) => (
                <div key={category} className="bg-gray-50 p-5 rounded-lg">
                  <h4 className="font-semibold text-gray-800 mb-3 text-lg">{category}</h4>
                  <div className="space-y-3">
                    {skills.map((skill, index) => {
                      const confidence = skillConfidenceMap[skill] || 'practice';
                      const isKnown = confidence === 'know';
                      
                      return (
                        <div key={index} className="flex items-center justify-between p-3 bg-white rounded-lg border">
                          <span className="font-medium text-gray-800">{skill}</span>
                          <button
                            onClick={() => handleSkillToggle(skill, confidence)}
                            className={`px-3 py-1 rounded-full text-sm font-medium transition-colors ${
                              isKnown
                                ? 'bg-green-100 text-green-800 hover:bg-green-200'
                                : 'bg-yellow-100 text-yellow-800 hover:bg-yellow-200'
                            }`}
                          >
                            {isKnown ? 'I know this' : 'Need practice'}
                          </button>
                        </div>
                      );
                    })}
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}

        {activeTab === 'checklist' && (
          <div>
            <h3 className="text-xl font-semibold text-gray-900 mb-6">Round-wise Preparation Checklist</h3>
            <div className="space-y-6">
              {Object.entries(analysisData.checklist).map(([round, items]) => (
                <div key={round} className="border border-gray-200 rounded-lg p-5">
                  <h4 className="font-semibold text-gray-800 mb-4 text-lg">{round}</h4>
                  <ul className="space-y-2">
                    {items.map((item, index) => (
                      <li key={index} className="flex items-start">
                        <div className="flex-shrink-0 mt-1">
                          <div className="w-3 h-3 bg-primary-500 rounded-full"></div>
                        </div>
                        <p className="ml-3 text-gray-700">{item}</p>
                      </li>
                    ))}
                  </ul>
                </div>
              ))}
            </div>
          </div>
        )}

        {activeTab === 'plan' && (
          <div>
            <h3 className="text-xl font-semibold text-gray-900 mb-6">7-Day Preparation Plan</h3>
            <div className="space-y-6">
              {Object.entries(analysisData.plan).map(([day, items]) => (
                <div key={day} className="border border-gray-200 rounded-lg p-5">
                  <h4 className="font-semibold text-gray-800 mb-4 text-lg">{day}</h4>
                  <ul className="space-y-2">
                    {items.map((item, index) => (
                      <li key={index} className="flex items-start">
                        <div className="flex-shrink-0 mt-1">
                          <div className="w-2 h-2 bg-primary-400 rounded-full"></div>
                        </div>
                        <p className="ml-3 text-gray-700">{item}</p>
                      </li>
                    ))}
                  </ul>
                </div>
              ))}
            </div>
          </div>
        )}

        {activeTab === 'questions' && (
          <div>
            <h3 className="text-xl font-semibold text-gray-900 mb-6">Likely Interview Questions</h3>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              {analysisData.questions.map((question, index) => (
                <div key={index} className="bg-gray-50 p-5 rounded-lg">
                  <div className="flex items-start">
                    <span className="flex-shrink-0 w-8 h-8 bg-primary-100 text-primary-800 rounded-full flex items-center justify-center text-sm font-medium mr-3">
                      {index + 1}
                    </span>
                    <p className="text-gray-800">{question}</p>
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}
      </div>

      {/* Action Next Box */}
      <div className="card">
        <h3 className="text-xl font-semibold text-gray-900 mb-4">Next Steps</h3>
        {weakSkills.length > 0 ? (
          <div className="bg-yellow-50 border border-yellow-200 rounded-lg p-5">
            <h4 className="font-medium text-yellow-800 mb-3">Skills to Focus On:</h4>
            <div className="flex flex-wrap gap-2 mb-4">
              {weakSkills.map((item, index) => (
                <span key={index} className="bg-yellow-100 text-yellow-800 px-3 py-1 rounded-full text-sm">
                  {item.skill} ({item.category})
                </span>
              ))}
            </div>
            <p className="text-yellow-700 font-medium">Start Day 1 plan now to strengthen these areas.</p>
          </div>
        ) : (
          <div className="bg-green-50 border border-green-200 rounded-lg p-5">
            <p className="text-green-700 font-medium">Great job! You've marked all skills as known. Continue with your preparation plan.</p>
          </div>
        )}
      </div>

      {/* Company Intel Section */}
      {analysisData.company && analysisData.company.trim() !== '' && (
        <CompanyIntel 
          companyName={analysisData.company} 
          extractedSkills={analysisData.extractedSkills}
          analysisId={id}
        />
      )}
    </div>
  );
};

export default ResultsPage;